development: &dev
  adapter: mysql
  database: invoicer_development
  username: root
  password: 
  host: 127.0.0.1

test: &test
  <<: *dev
  database: invoicer_test

production:
  <<: *dev
  database: invoicer_production



cucumber:
  <<: *test