development: &dev
  adapter: mysql
  database: invoicer_development
  username: invoicer
  password: invoicer
  host: 127.0.0.1

test:
  <<: *dev
  database: invoicer_test

production:
  <<: *dev
  database: invoicer_production


